services:
  server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    container_name: ${VAULT_DOCKER_SERVER_CONTAINER}
    ports:
      - "${VAULT_DOCKER_SERVER_HOST_PORT}:${VAULT_SERVER_PORT}"
    volumes:
      - "${VAULT_DOCKER_SERVER_DATA}:/app/data/server"
    environment:
      PYTHONPATH: ${VAULT_DOCKER_PYTHONPATH}
      VAULT_SERVER_BIND_HOST: ${VAULT_SERVER_BIND_HOST}
      VAULT_SERVER_PORT: ${VAULT_SERVER_PORT}
      VAULT_SERVER_DB_PATH: ${VAULT_DOCKER_SERVER_DB_PATH}

  client:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    container_name: ${VAULT_DOCKER_CLIENT_CONTAINER}
    depends_on:
      - server
    volumes:
      - "${VAULT_DOCKER_CLIENT_DATA}:/app/data/client"
    environment:
      PYTHONPATH: ${VAULT_DOCKER_PYTHONPATH}
      VAULT_SERVER_URL: ${VAULT_DOCKER_SERVER_URL}
      VAULT_CLIENT_DATA_DIR: ${VAULT_DOCKER_CLIENT_DATA_DIR}